apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.18
    max_hamming: 0
    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: 1
      sharpening: 0.25
    pose_estimation_method: pnp
    tag:
      ids: [0, 1, 2]
      frames: [tag_home, tag_turn, tag_pickup]
      sizes: [0.18, 0.18, 0.18]
